import './js/slider';
import './js/categories';
import './js/search';
import './js/filters';
import './js/gallery';
import './js/header';
import './js/pagination';
import './js/modals';
import './js/popular-recipes';
